#!/bin/sh
#
# A pre-commit hook that enforces formatting checks by
# calling an associated python script for checking.
# 
# Check the corresponding python script called below if
# there are any errors.
#
# To disable this pre-commit check entirely, rename this file
# to 'pre-commit.disable'.

which python > /dev/null
if [ $? == 1 ] ; then
    echo "ERROR: Python is necessary to enable pre-commit checks"
    echo "use 'git commit --no-verify' to skip pre-commit checks temporarily"
    echo "git commit NOT successful"
    exit 1
else
    python .git/hooks/pre-commit.py
    exit $?
fi